### ISSUE TITLE
feat proposal: a divider between the dock-items

### ISSUE THREAD

**Issue by LoTwT** [CatsJuice/dockbar#12]
### expected

a divider like Mac OS dock bar divider as following

<img width="87" alt="image" src="https://github.com/CatsJuice/dockbar/assets/50254496/fb9579aa-e25b-4baf-b53a-9153b9bff6f4">

### implementation discussion

- Should it be a component like `dock-divider`?
- Or a prop on the `dock-item`?
- other choices

**Comment by CatsJuice** [comment]
It's possible to implement it by adding a custom `div` under `<dock-wrapper>`: [Codepen Example](https://codepen.io/catsjuice/pen/GRwQdza)

```html
<dock-wrapper id="dock">
  <dock-item>
    <div class="item">1</div>
  </dock-item>

  <!-- insert a custom element -->
  <div class="splitter"></div>

  <dock-item>
    <div class="item">2</div>
  </dock-item>
</dock-wrapper>
```

**Comment by LoTwT** [comment]
> 

Thanks! I will try!
