### ISSUE TITLE
Formatting HTML Breaks This Package

### ISSUE THREAD

**Issue by tcalexwang** [CatsJuice/dockbar#2]
## Issue: Formatting HTML Breaks This Package

**Description**
When formatting the HTML(usually done by VS Code's auto formatting), the component does not behave as expected. The issue occurs when the HTML is **formatted with indents and newline characters**. The non-formatted version of the HTML works fine, but after formatting, the functionality breaks.

**Steps to reproduce**
1. In `packages/dockbar/index.html`, add a new hardcoded dock-item in the dock wrapper
	```
	<dock-wrapper class="glass" id="dock">
		<dock-item><div class="my-item full flex-center">T</div></dock-item>
	</dock-wrapper>
	```
	this went well as expected

2. Format the code above as
	```
	<dock-wrapper class="glass" id="dock">
	  <dock-item>
	    <div class="my-item full flex-center">T</div>
	  </dock-item>
	</dock-wrapper>
	```
	then the dock became static with wrong styles. 
	<img width="263" alt="CleanShot 2023-07-15 at 15 00 26@2x" 				src="https://github.com/CatsJuice/dockbar/assets/34364810/a5a48fd2-3e89-42c8-bef4-4114f188cae5">

**Environment**
- OS: macOS Ventura & Ubuntu 22 LTS
- Node Version: 20.4.0
- pnpm version: 8.6.6
- Browser: Chrome
- Package Version: 0.1.0

**Additional context**
I initially encountered this issue when using VS Code, which automatically formats HTML on save. This issue could be a major inconvenience for developers who have auto-formatting enabled in their IDEs.

**Comment by CatsJuice** [comment]
🙏 Thanks!!! @chang2000 

This issue is important for me, it helps me find some edge case that I had encountered before.
It should be fixed in [v0.1.1](https://github.com/CatsJuice/dockbar/releases/tag/v0.1.1). And I've updated my [Codepen example](https://codepen.io/catsjuice/pen/GRwQdza?editors=1100), it works now.


Feel free to reopen the issue if the problem still exists!
