### ISSUE TITLE
the dockbar doesn't display in the playground

### ISSUE THREAD

**Issue by LoTwT** [CatsJuice/dockbar#9]
## issue

When I open the playground, the dockbar doesn't display. The error is following

<img width="842" alt="image" src="https://github.com/CatsJuice/dockbar/assets/50254496/15ff5d98-5e23-4214-aa52-c89f28163ac8">

## try

It seems related to this commit https://github.com/CatsJuice/dockbar/commit/6a700ea20b0cf146b9a7410d105d2939f36e11b9.

So what's wrong with the export definition including `dist` ?

**Comment by CatsJuice** [comment]
Yes, that's some problem with the design of the `dist` product structure. This should be resolve in 35a4837e4f52f3f9f0b3dc94a2c0f063039e6980, 🤣 although the solution is really a hack!

**Comment by CatsJuice** [comment]
The `dist` directory is designed for publishing to npm, while what is referenced in the `playground` is actually non-existent during the development phase as it is within the repository.

**Comment by LoTwT** [comment]
> Yes, that's some problem with the design of the `dist` product structure. This should be resolve in [35a4837](https://github.com/CatsJuice/dockbar/commit/35a4837e4f52f3f9f0b3dc94a2c0f063039e6980), 🤣 although the solution is really a hack!

I make #10 to find a better way to solve it. We can discuss it there. 😄
